name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Tests and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest backend --cov=backend --cov-report=xml
          
      - name: Upload coverage report to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan
        run: |
          sonar-scanner
